name: Playwright Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Playwright dependencies
        run: npx playwright install --with-deps

      - name: Install project dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test --reporter=json > test-results.json
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        continue-on-error: true

      - name: Send Slack Notification
        run: node send-slack-report.js
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        continue-on-error: true  # This step will always run, even if previous steps fail
